### ISSUE TITLE
Adding a "0" to the wrong number hash

### ISSUE THREAD

**Issue by taranasus** [fudgebucket27/PoseidonSharp#22]
https://github.com/fudgebucket27/PoseidonSharp/blob/d5e0d70c80b9d8759b0ef75fe2e66850c0d48eff/PoseidonSharp/SHA256Helper.cs#L29

Hey fudgy, little bug for ya. So on that line what you're doing is you're taking the base10 number you get from the sha256HashString and converting it to base16 and adding a zero to that.

This is wrong, because the result you get from sha256HashNumber.ToString("x2") is not the same as the original sha256HashBytes when it's a negative number. I wouldn't be able to say why, but it just is. What you should be doing is:

string sha256HashAsPositiveHexString = "0" + sha256HashString;

I've gotten a few times a bug with that line and this seems to fix it ;) Good luck!

**Comment by fudgebucket27** [comment]
Fixed
